<?php
/**
 * Function to register custom fields.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package bigbang
 */

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_component_item_callout',
	'title' => 'component-item-callout',
	'fields' => array(
		array(
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array(
				'left' => 'Left',
				'right' => 'Right',
			),
			'default_value' => array(
				0 => 'left',
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'component_item_callout_field_initial_orientation',
			'label' => 'Initial Image Orientation',
			'name' => 'initial_orientation',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
		),
		array(
			'default_value' => 0,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'key' => 'component_item_callout_field_rounded_img',
			'label' => 'Rounded Image',
			'name' => 'rounded_img',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
		),
		array(
			'default_value' => 0,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'key' => 'component_item_callout_field_remove_gutter',
			'label' => 'Remove Gutter',
			'name' => 'remove_gutter',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
		),
		array(
			'key' => 'component_item_callout_field_item_callout',
			'label' => 'Item Callout',
			'name' => 'item_callout',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Row',
			'collapsed' => 'component_item_callout_field_image',
			'sub_fields' => array(
				array(
					'clone' => array(
						0 => 'component_heading_field_headline_tag',
						1 => 'component_heading_field_tagline',
						2 => 'component_heading_field_headline',
						3 => 'component_heading_field_description',
					),
					'prefix_label' => 0,
					'prefix_name' => 0,
					'display' => 'seamless',
					'layout' => 'group',
					'key' => 'component_item_callout_field_item_heading',
					'label' => 'Item Heading',
					'name' => 'item_heading',
					'type' => 'clone',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array(
					'key' => 'component_item_callout_field_image',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'component_item_callout_field_video_src',
					'label' => 'Add Video',
					'name' => 'video_src',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'component_item_callout_field_rounded_img',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'disable' => 'Disable',
						'youtube' => 'Youtube',
						'vimeo' => 'Vimeo',
					),
					'default_value' => array(
						0 => 'novideo',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array(
					'key' => 'component_item_callout_field_video_id',
					'label' => 'Video ID',
					'name' => 'video_id',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'component_item_callout_field_video_src',
								'operator' => '==',
								'value' => 'youtube',
							),
							array(
								'field' => 'component_item_callout_field_rounded_img',
								'operator' => '!=',
								'value' => '1',
							),
						),
						array(
							array(
								'field' => 'component_item_callout_field_video_src',
								'operator' => '==',
								'value' => 'vimeo',
							),
							array(
								'field' => 'component_item_callout_field_rounded_img',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'clone' => array(
						1 => 'group_component_button',
					),
					'prefix_label' => 0,
					'prefix_name' => 0,
					'display' => 'group',
					'layout' => 'block',
					'key' => 'component_item_callout_field_button_link',
					'label' => 'Item Button',
					'name' => 'button_link',
					'type' => 'clone',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
			),
		),
		array(
			'clone' => array(
				1 => 'group_component_button',
			),
			'prefix_label' => 0,
			'prefix_name' => 0,
			'display' => 'seamless',
			'layout' => 'block',
			'key' => 'component_item_callout_field_module_link',
			'label' => 'Module Button',
			'name' => 'module_link',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

endif;
